<?php
declare(strict_types=1);
require __DIR__ . '/../config/config.php';
function h($v){return htmlspecialchars((string)($v??''),ENT_QUOTES,'UTF-8');}
$action=$_GET['action']??'view';
if($_SERVER['REQUEST_METHOD']==='POST' && $action==='receive'){
 $medicineId=(int)($_POST['medicine_id']??0);$boxes=max(0,(int)($_POST['boxes']??0));$strips=max(0,(int)($_POST['strips']??0));$units=max(0,(int)($_POST['units']??0));$batch=trim($_POST['batch_no']??'');$expiry=trim($_POST['expiry_date']??'')?:null;
 $m=db()->prepare('SELECT * FROM medicines WHERE id=? AND active=1');$m->execute([$medicineId]);$medicine=$m->fetch();
 if(!$medicine)exit('Medicine not found.');
 $total=$boxes*(int)$medicine['strips_per_box']*(int)$medicine['units_per_strip']+$strips*(int)$medicine['units_per_strip']+$units;
 if($total<1)exit('Enter at least one box, strip, or tablet.');
 $s=db()->prepare('INSERT INTO batches (medicine_id,batch_no,expiry_date,units_received,units_remaining,purchase_unit_cost) VALUES (?,?,?,?,?,?)');
 $s->execute([$medicineId,$batch?:null,$expiry,$total,$total,max(0,(float)($_POST['purchase_unit_cost']??0))]);$bid=(int)db()->lastInsertId();
 db()->prepare('INSERT INTO stock_movements (medicine_id,batch_id,movement_type,quantity_units,note) VALUES (?,?,"purchase",?,?)')->execute([$medicineId,$bid,$total,'Stock received']);
 header('Location: inventory.php?saved=1');exit;
}
$meds=db()->query('SELECT id,name,units_per_strip,strips_per_box FROM medicines WHERE active=1 ORDER BY name')->fetchAll();
$rows=db()->query('SELECT m.id,m.name,m.units_per_strip,m.strips_per_box,m.reorder_level,COALESCE(SUM(b.units_remaining),0) stock FROM medicines m LEFT JOIN batches b ON b.medicine_id=m.id WHERE m.active=1 GROUP BY m.id ORDER BY m.name')->fetchAll();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Inventory · <?=h(APP_NAME)?></title><link rel="stylesheet" href="style.css"></head><body><header><div class="brand">💊 <?=h(APP_NAME)?></div><nav><a href="index.php">Dashboard</a><a href="pos.php">POS</a><a href="index.php?action=medicines">Medicines</a><a class="active" href="inventory.php">Inventory</a><a href="index.php?action=reports">Reports</a></nav></header><main><div class="page-title"><div><div class="eyebrow">STOCK CONTROL</div><h1>Inventory</h1><p>Batch number and expiry date are both optional.</p></div></div><?php if(isset($_GET['saved'])):?><div class="success">✓ Stock received successfully.</div><?php endif;?><section class="panel"><h2>Receive Stock</h2><form method="post" action="inventory.php?action=receive" class="grid"><select name="medicine_id" required><option value="">Select medicine *</option><?php foreach($meds as $m):?><option value="<?=$m['id']?>"><?=h($m['name'])?> · <?=$m['units_per_strip']?>/strip · <?=$m['strips_per_box']?> strips/box</option><?php endforeach;?></select><label>Batch Number <span class="optional">(optional)</span><input name="batch_no" placeholder="Leave blank if not available"></label><label>Expiry Date <span class="optional">(optional)</span><input type="date" name="expiry_date"></label><label>Boxes<input type="number" name="boxes" min="0" value="0"></label><label>Strips<input type="number" name="strips" min="0" value="0"></label><label>Loose Tablets<input type="number" name="units" min="0" value="0"></label><label>Purchase Cost / Tablet<input type="number" step="0.0001" name="purchase_unit_cost" min="0" value="0"></label><button class="btn">Receive Stock</button></form></section><section class="panel"><h2>Current Stock</h2><table><tr><th>Medicine</th><th>Pack</th><th>Stock</th><th>Reorder</th></tr><?php foreach($rows as $r):?><tr><td><b><?=h($r['name'])?></b></td><td><?=$r['units_per_strip']?> tablets/strip × <?=$r['strips_per_box']?> strips/box</td><td><b><?=number_format((int)$r['stock'])?></b> tablets</td><td><?=number_format((int)$r['reorder_level'])?></td></tr><?php endforeach;?></table></section></main></body></html>