<?php
declare(strict_types=1); require __DIR__.'/../config/config.php';
$db=db(); $tab=$_GET['tab']??'inventory'; $msg='';
function go($t){header('Location: manage.php?tab='.urlencode($t));exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  $a=$_POST['action']??'';
  if($a==='supplier'){$db->prepare('INSERT INTO suppliers(name,phone,address) VALUES(?,?,?)')->execute([trim($_POST['name']),trim($_POST['phone']??''),trim($_POST['address']??'')]);go('suppliers');}
  if($a==='customer'){$db->prepare('INSERT INTO customers(name,phone,address) VALUES(?,?,?)')->execute([trim($_POST['name']),trim($_POST['phone']??''),trim($_POST['address']??'')]);go('customers');}
  if($a==='expense'){$db->prepare('INSERT INTO expenses(category,description,amount) VALUES(?,?,?)')->execute([trim($_POST['category']),trim($_POST['description']??''),max(0,(float)$_POST['amount'])]);go('expenses');}
  if($a==='stock'){$mid=(int)$_POST['medicine_id'];$boxes=max(0,(int)$_POST['boxes']);$strips=max(0,(int)$_POST['strips']);$tabs=max(0,(int)$_POST['tablets']);$m=$db->prepare('SELECT * FROM medicines WHERE id=?');$m->execute([$mid]);$m=$m->fetch();if(!$m)throw new RuntimeException('Medicine not found');$units=$boxes*(int)$m['units_per_strip']*(int)$m['strips_per_box']+$strips*(int)$m['units_per_strip']+$tabs;if($units<1)throw new RuntimeException('Enter stock quantity');$db->beginTransaction();$db->prepare('INSERT INTO batches(medicine_id,batch_no,expiry_date,units_received,units_remaining,purchase_unit_cost) VALUES(?,?,?,?,?,?)')->execute([$mid,trim($_POST['batch_no']??'')?:null,$_POST['expiry_date']?:null,$units,$units,max(0,(float)$_POST['cost'])]);$bid=(int)$db->lastInsertId();$db->prepare("INSERT INTO stock_movements(medicine_id,batch_id,movement_type,quantity_units,note) VALUES(? ,?,'purchase',?,?)")->execute([$mid,$bid,$units,'Manual stock receipt']);$db->commit();go('inventory');}
  if($a==='adjust'){$bid=(int)$_POST['batch_id'];$delta=(int)$_POST['delta'];$db->beginTransaction();$q=$db->prepare('SELECT * FROM batches WHERE id=? FOR UPDATE');$q->execute([$bid]);$b=$q->fetch();if(!$b||$b['units_remaining']+$delta<0)throw new RuntimeException('Invalid adjustment');$db->prepare('UPDATE batches SET units_remaining=units_remaining+? WHERE id=?')->execute([$delta,$bid]);$db->prepare("INSERT INTO stock_movements(medicine_id,batch_id,movement_type,quantity_units,note) VALUES(?,?, 'adjustment',?,?)")->execute([$b['medicine_id'],$bid,$delta,trim($_POST['note']??'Adjustment')]);$db->commit();go('inventory');}
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();$msg=$e->getMessage();}
}
$meds=$db->query("SELECT m.*,COALESCE((SELECT SUM(units_remaining) FROM batches b WHERE b.medicine_id=m.id),0) stock FROM medicines m WHERE m.active=1 ORDER BY m.name")->fetchAll();
$batches=$db->query("SELECT b.*,m.name FROM batches b JOIN medicines m ON m.id=b.medicine_id ORDER BY (b.expiry_date IS NULL),b.expiry_date,b.id DESC")->fetchAll();
$suppliers=$db->query('SELECT * FROM suppliers ORDER BY name')->fetchAll();$customers=$db->query('SELECT * FROM customers ORDER BY name')->fetchAll();$expenses=$db->query('SELECT * FROM expenses ORDER BY id DESC LIMIT 100')->fetchAll();
$salesToday=(float)$db->query("SELECT COALESCE(SUM(total),0) FROM sales WHERE DATE(created_at)=CURDATE()")->fetchColumn();$profitBase=(float)$db->query("SELECT COALESCE(SUM(si.line_total-(si.quantity_units*m.purchase_price)),0) FROM sale_items si JOIN medicines m ON m.id=si.medicine_id JOIN sales s ON s.id=si.sale_id WHERE DATE(s.created_at)=CURDATE()")->fetchColumn();$expenseToday=(float)$db->query("SELECT COALESCE(SUM(amount),0) FROM expenses WHERE DATE(created_at)=CURDATE()")->fetchColumn();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Management • <?=e(APP_NAME)?></title><link rel="stylesheet" href="style.css"></head><body><header><div class="brand">💊 <?=e(APP_NAME)?></div><nav><a href="index.php">Dashboard</a><a href="pos.php">POS</a><a href="index.php?action=medicines">Medicines</a><a href="inventory.php">Inventory</a><a class="active" href="manage.php">Management</a></nav></header><main><h1><?=ucfirst(e($tab))?></h1><?php if($msg):?><div class="alert"><?=e($msg)?></div><?php endif;?><div class="tabs"><?php foreach(['inventory','purchases','suppliers','customers','expenses','returns','reports','users'] as $t):?><a class="<?=$tab===$t?'active':''?>" href="manage.php?tab=<?=$t?>"><?=ucfirst($t)?></a><?php endforeach;?></div>
<?php if($tab==='inventory'): ?><section class="panel"><h2>Receive Stock</h2><p>Batch number and expiry date are optional.</p><form method="post" class="formrow"><input type="hidden" name="action" value="stock"><label>Medicine<select name="medicine_id" required><option value="">Select</option><?php foreach($meds as $m):?><option value="<?=$m['id']?>"><?=e($m['name'])?></option><?php endforeach;?></select></label><label>Batch <input name="batch_no" placeholder="Optional"></label><label>Expiry <input name="expiry_date" type="date"></label><label>Cost / unit <input name="cost" type="number" min="0" step="0.0001" value="0"></label><label>Boxes <input name="boxes" type="number" min="0" value="0"></label><label>Strips <input name="strips" type="number" min="0" value="0"></label><label>Loose tablets <input name="tablets" type="number" min="0" value="0"></label><button class="btn">Receive Stock</button></form></section><section class="panel"><h2>Current Stock & Batches</h2><table><tr><th>Medicine</th><th>Batch</th><th>Expiry</th><th>Remaining</th><th>Adjustment</th></tr><?php foreach($batches as $b):?><tr><td><?=e($b['name'])?></td><td><?=e($b['batch_no']??'—')?></td><td><?=e($b['expiry_date']??'—')?></td><td><?=number_format($b['units_remaining'])?></td><td><form method="post"><input type="hidden" name="action" value="adjust"><input type="hidden" name="batch_id" value="<?=$b['id']?>"><input name="delta" type="number" placeholder="+/-"><input name="note" placeholder="Reason"><button class="btn">Apply</button></form></td></tr><?php endforeach;?></table></section>
<?php elseif($tab==='suppliers'):?><section class="panel"><h2>Add Supplier</h2><form method="post"><input type="hidden" name="action" value="supplier"><input name="name" placeholder="Name" required><input name="phone" placeholder="Phone"><input name="address" placeholder="Address"><button class="btn">Save Supplier</button></form></section><section class="panel"><table><tr><th>Name</th><th>Phone</th><th>Address</th><th>Balance</th></tr><?php foreach($suppliers as $s):?><tr><td><?=e($s['name'])?></td><td><?=e($s['phone'])?></td><td><?=e($s['address'])?></td><td>Rs. <?=money((float)$s['balance'])?></td></tr><?php endforeach;?></table></section>
<?php elseif($tab==='customers'):?><section class="panel"><h2>Add Customer</h2><form method="post"><input type="hidden" name="action" value="customer"><input name="name" placeholder="Name" required><input name="phone" placeholder="Phone"><input name="address" placeholder="Address"><button class="btn">Save Customer</button></form></section><section class="panel"><table><tr><th>Name</th><th>Phone</th><th>Address</th></tr><?php foreach($customers as $c):?><tr><td><?=e($c['name'])?></td><td><?=e($c['phone'])?></td><td><?=e($c['address'])?></td></tr><?php endforeach;?></table></section>
<?php elseif($tab==='expenses'):?><section class="panel"><h2>Add Expense</h2><form method="post"><input type="hidden" name="action" value="expense"><input name="category" placeholder="Category" required><input name="description" placeholder="Description"><input name="amount" type="number" min="0" step="0.01" placeholder="Amount" required><button class="btn">Record Expense</button></form></section><section class="panel"><table><tr><th>Date</th><th>Category</th><th>Description</th><th>Amount</th></tr><?php foreach($expenses as $x):?><tr><td><?=e($x['created_at'])?></td><td><?=e($x['category'])?></td><td><?=e($x['description'])?></td><td>Rs. <?=money((float)$x['amount'])?></td></tr><?php endforeach;?></table></section>
<?php elseif($tab==='reports'):?><section class="panel"><h2>Today's Summary</h2><p>Sales: <b>Rs. <?=money($salesToday)?></b> &nbsp; Gross Profit: <b>Rs. <?=money($profitBase)?></b> &nbsp; Expenses: <b>Rs. <?=money($expenseToday)?></b></p></section><section class="panel"><h2>Expiry Alerts — 90 Days</h2><table><tr><th>Medicine</th><th>Batch</th><th>Expiry</th><th>Units</th></tr><?php foreach($batches as $b): ?><?php if($b['expiry_date']&&$b['expiry_date']<=date('Y-m-d',strtotime('+90 days'))): ?><tr><td><?=e($b['name'])?></td><td><?=e($b['batch_no']??'—')?></td><td><?=e($b['expiry_date'])?></td><td><?=number_format($b['units_remaining'])?></td></tr><?php endif; ?><?php endforeach; ?></table></section>
<?php elseif($tab==='purchases'):?><section class="panel"><h2>Purchasing</h2><p>Receive stock through the Inventory tab and select a supplier from Suppliers.</p></section>
<?php elseif($tab==='returns'):?><section class="panel"><h2>Returns</h2><p>Return workflow will be connected to sales history and batches in the next step.</p></section>
<?php else:?><section class="panel"><h2>User & Roles</h2><p>Supported roles: Admin, Manager, Pharmacist and Cashier.</p></section><?php endif;?></main></body></html>