<?php
declare(strict_types=1);
require __DIR__ . '/../config/config.php';
$meds=db()->query('SELECT m.*,COALESCE(SUM(b.units_remaining),0) stock FROM medicines m LEFT JOIN batches b ON b.medicine_id=m.id WHERE m.active=1 GROUP BY m.id ORDER BY m.name')->fetchAll();
function e2(?string $v):string{return htmlspecialchars($v??'',ENT_QUOTES,'UTF-8');}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fast POS · <?=e2(APP_NAME)?></title><link rel="stylesheet" href="style.css"></head><body>
<header><div class="brand">💊 <?=e2(APP_NAME)?></div><nav><a href="index.php?action=dashboard">Dashboard</a><a class="active" href="pos.php">POS</a><a href="index.php?action=medicines">Medicines</a><a href="index.php?action=inventory">Inventory</a><a href="index.php?action=reports">Reports</a></nav></header>
<main><div class="page-title"><div><div class="eyebrow">POINT OF SALE</div><h1>Fast Sale</h1><p>Scan a barcode or search. Sell boxes, strips, or individual tablets without manual calculations.</p></div><div class="pos-status">● Ready</div></div>
<div class="pos"><section class="panel"><input id="search" autocomplete="off" placeholder="🔎 Search medicine or scan barcode" autofocus><div class="hint">Press Enter after scanning · Click a medicine to add it</div><div id="results"></div></section>
<section class="panel cart-panel"><div class="cart-head"><div><h2>Current Sale</h2><span id="count">0 units</span></div><button class="clear-btn" onclick="clearCart()">Clear</button></div><div id="cart"></div><div class="totals"><div>Subtotal <b>Rs. <span id="subtotal">0.00</span></b></div><label>Discount <input id="discount" type="number" value="0" min="0" step="0.01"></label><div class="grand">Total <strong>Rs. <span id="total">0.00</span></strong></div></div><div class="pay-grid"><select id="payment"><option value="cash">💵 Cash</option><option value="card">💳 Card</option><option value="credit">👤 Credit</option></select><input id="paid" type="number" min="0" step="0.01" placeholder="Amount received"></div><button class="btn checkout" onclick="checkout()">Complete Sale →</button></section></div></main>
<script>
const medicines=<?=json_encode($meds,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;
let cart=[];
const fmt=n=>Number(n).toFixed(2);
function pack(m,type){if(type==='box')return {label:'Box',units:Number(m.units_per_strip)*Number(m.strips_per_box),price:Number(m.retail_unit_price)*Number(m.units_per_strip)*Number(m.strips_per_box)};if(type==='strip')return {label:'Strip',units:Number(m.units_per_strip),price:Number(m.retail_unit_price)*Number(m.units_per_strip)};return {label:m.unit_name||'Tablet',units:1,price:Number(m.retail_unit_price)};}
function renderResults(){const q=document.getElementById('search').value.toLowerCase().trim();const rs=medicines.filter(m=>(m.name+' '+(m.generic_name||'')+' '+(m.strength||'')+' '+(m.barcode||'')).toLowerCase().includes(q)).slice(0,15);document.getElementById('results').innerHTML=rs.map(m=>`<button class="result" onclick="add(${m.id},'unit')"><span><b>${esc(m.name)}</b><small>${esc((m.generic_name||'')+' '+(m.strength||''))} · Stock ${m.stock} units${m.barcode?' · '+esc(m.barcode):''}</small></span><strong>Rs. ${fmt(m.retail_unit_price)} / ${esc(m.unit_name)}</strong></button>`).join('')}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function add(id,type){const m=medicines.find(x=>Number(x.id)===Number(id));if(!m||Number(m.stock)<1)return;const p=pack(m,type);if(p.units>Number(m.stock))return alert('Not enough stock for one '+p.label+'.');const key=id+'-'+type;let x=cart.find(v=>v.key===key);if(x){if((x.qty+1)*x.units>Number(m.stock))return alert('Not enough stock.');x.qty++;}else cart.push({key,id:Number(id),name:m.name,type,units:p.units,price:p.price,qty:1,max:Number(m.stock),unitLabel:p.label});renderCart();}
function remove(i){cart.splice(i,1);renderCart();}
function setQty(i,v){const n=Math.max(1,parseInt(v)||1);if(n*cart[i].units>cart[i].max)return alert('Not enough stock.');cart[i].qty=n;renderCart();}
function changeType(i,type){const x=cart[i],m=medicines.find(v=>Number(v.id)===x.id),p=pack(m,type);if(p.units*x.qty>Number(m.stock))return alert('Not enough stock for this pack.');x.type=type;x.units=p.units;x.price=p.price;x.unitLabel=p.label;x.key=x.id+'-'+type;renderCart();}
function renderCart(){document.getElementById('cart').innerHTML=cart.length?cart.map((x,i)=>`<div class="cartrow"><div class="item-main"><b>${esc(x.name)}</b><small>${x.qty} × ${x.unitLabel} · ${x.units*x.qty} ${x.units*x.qty===1?'unit':'units'}</small><div class="unit-switch"><button class="${x.type==='box'?'selected':''}" onclick="changeType(${i},'box')">Box</button><button class="${x.type==='strip'?'selected':''}" onclick="changeType(${i},'strip')">Strip</button><button class="${x.type==='unit'?'selected':''}" onclick="changeType(${i},'unit')">${esc(x.unitLabel==='Tablet'?'Tablet':(medicines.find(m=>m.id===x.id)?.unit_name||'Unit'))}</button></div></div><input class="qty" type="number" min="1" value="${x.qty}" onchange="setQty(${i},this.value)"><b>Rs. ${fmt(x.price*x.qty)}</b><button class="remove" onclick="remove(${i})">×</button></div>`).join(''):'<div class="empty"><div class="empty-icon">🛒</div><b>No items yet</b><small>Search or scan a medicine to start the sale.</small></div>';const s=cart.reduce((a,x)=>a+x.price*x.qty,0),d=Math.max(0,Number(document.getElementById('discount').value)||0);document.getElementById('count').textContent=cart.reduce((a,x)=>a+x.units*x.qty,0)+' units';document.getElementById('subtotal').textContent=fmt(s);document.getElementById('total').textContent=fmt(Math.max(0,s-d));}
function clearCart(){cart=[];renderCart();document.getElementById('search').focus();}
function checkout(){if(!cart.length)return alert('Cart is empty.');const d=Math.max(0,Number(document.getElementById('discount').value)||0),s=cart.reduce((a,x)=>a+x.price*x.qty,0),t=Math.max(0,s-d),paid=Number(document.getElementById('paid').value)||t;const items=cart.map(x=>({id:x.id,name:x.name,qty:x.units*x.qty,price:x.price/x.units}));const f=document.createElement('form');f.method='post';f.action='index.php?action=sale';[['items',JSON.stringify(items)],['discount',d],['payment_method',document.getElementById('payment').value],['paid',paid]].forEach(([n,v])=>{const i=document.createElement('input');i.type='hidden';i.name=n;i.value=v;f.appendChild(i)});document.body.appendChild(f);f.submit();}
document.getElementById('search').addEventListener('input',renderResults);document.getElementById('search').addEventListener('keydown',e=>{if(e.key==='Enter'){const first=document.querySelector('.result');if(first)first.click();}});document.getElementById('discount').addEventListener('input',renderCart);renderResults();renderCart();
</script></body></html>
