<?php
declare(strict_types=1);
require __DIR__ . '/../config/config.php';
$meds=db()->query('SELECT m.*,COALESCE(SUM(b.units_remaining),0) stock FROM medicines m LEFT JOIN batches b ON b.medicine_id=m.id WHERE m.active=1 GROUP BY m.id ORDER BY m.name')->fetchAll();
$customers=db()->query('SELECT id,name,phone FROM customers ORDER BY name')->fetchAll();
function e2(?string $v):string{return htmlspecialchars($v??'',ENT_QUOTES,'UTF-8');}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fast POS · <?=e2(APP_NAME)?></title><link rel="stylesheet" href="style.css"></head><body>
<header><div class="brand">💊 <?=e2(APP_NAME)?></div><nav><a href="index.php?action=dashboard">Dashboard</a><a class="active" href="index.php?action=pos">POS</a><a href="index.php?action=medicines">Medicines</a><a href="index.php?action=inventory">Inventory</a><a href="index.php?action=reports">Reports</a></nav></header>
<main><div class="page-title"><div><div class="eyebrow">POINT OF SALE</div><h1>Fast Sale</h1><p>Scan a barcode or search. Choose Box, Strip, or Tablet.</p></div><div class="pos-status">● Ready</div></div>
<div class="pos"><section class="panel"><input id="search" autocomplete="off" placeholder="🔎 Search medicine or scan barcode" autofocus><div class="hint">Press Enter after scanning · Choose a selling unit below</div><div id="results"></div></section>
<section class="panel cart-panel"><div class="cart-head"><div><h2>Current Sale</h2><span id="count">0 units</span></div><button class="clear-btn" onclick="clearCart()">Clear</button></div><div id="cart"></div><div class="totals"><div>Subtotal <b>Rs. <span id="subtotal">0.00</span></b></div><label>Discount <input id="discount" type="number" value="0" min="0" step="0.01"></label><div class="grand">Total <strong>Rs. <span id="total">0.00</span></strong></div></div><div class="pay-grid"><select id="payment" onchange="paymentChanged()"><option value="cash">💵 Cash</option><option value="card">💳 Card</option><option value="credit">👤 Credit</option></select><input id="paid" type="number" min="0" step="0.01" placeholder="Amount received"></div><div id="customerWrap" style="display:none;margin-top:10px"><label>Customer for credit sale<select id="customer"><option value="">Select customer</option><?php foreach($customers as $c):?><option value="<?=$c['id']?>"><?=e2($c['name'])?><?= $c['phone']?' — '.e2($c['phone']):'' ?></option><?php endforeach;?></select></label><div style="margin-top:6px"><a href="customers.php" target="_blank">+ Add/manage customers</a></div></div><button class="btn checkout" onclick="checkout()">Complete Sale →</button></section></div></main>
<script>
const medicines=<?=json_encode($meds,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;let cart=[];const fmt=n=>Number(n).toFixed(2);
function pack(m,type){let u=Number(m.units_per_strip)||1,s=Number(m.strips_per_box)||1,p=Number(m.retail_unit_price)||0;if(type==='box')return{label:'Box',units:u*s,price:p*u*s};if(type==='strip')return{label:'Strip',units:u,price:p*u};return{label:m.unit_name||'Tablet',units:1,price:p};}
function renderResults(){const q=document.getElementById('search').value.toLowerCase().trim();const rs=medicines.filter(m=>(m.name+' '+(m.generic_name||'')+' '+(m.strength||'')+' '+(m.barcode||'')).toLowerCase().includes(q)).slice(0,15);document.getElementById('results').innerHTML=rs.map(m=>`<div class="result"><span><b>${esc(m.name)}</b><small>${esc((m.generic_name||'')+' '+(m.strength||''))} · Stock ${m.stock} units${m.barcode?' · '+esc(m.barcode):''}</small></span><div class="sell-buttons"><button class="btn mini" onclick="add(${m.id},'box')">BOX<br><small>Rs.${fmt(pack(m,'box').price)}</small></button><button class="btn mini" onclick="add(${m.id},'strip')">STRIP<br><small>Rs.${fmt(pack(m,'strip').price)}</small></button><button class="btn mini" onclick="add(${m.id},'unit')">${esc((m.unit_name||'TABLET').toUpperCase())}<br><small>Rs.${fmt(pack(m,'unit').price)}</small></button></div></div>`).join('');}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function add(id,type){const m=medicines.find(x=>Number(x.id)===Number(id));if(!m||Number(m.stock)<1)return;const p=pack(m,type);if(p.units>Number(m.stock))return alert('Not enough stock for one '+p.label+'.');const key=id+'-'+type;let x=cart.find(v=>v.key===key);if(x){if((x.qty+1)*x.units>Number(m.stock))return alert('Not enough stock.');x.qty++;}else cart.push({key,id:Number(id),name:m.name,type,units:p.units,price:p.price,qty:1,max:Number(m.stock),unitLabel:p.label});renderCart();}
function remove(i){cart.splice(i,1);renderCart();}function setQty(i,v){const n=Math.max(1,parseInt(v)||1);if(n*cart[i].units>cart[i].max)return alert('Not enough stock.');cart[i].qty=n;renderCart();}
function changeType(i,type){const x=cart[i],m=medicines.find(v=>Number(v.id)===x.id),p=pack(m,type);if(p.units*x.qty>Number(m.stock))return alert('Not enough stock for this pack.');x.type=type;x.units=p.units;x.price=p.price;x.unitLabel=p.label;x.key=x.id+'-'+type;renderCart();}
function renderCart(){document.getElementById('cart').innerHTML=cart.length?cart.map((x,i)=>`<div class="cartrow"><div class="item-main"><b>${esc(x.name)}</b><small>${x.qty} × ${x.unitLabel} · ${x.units*x.qty} units</small><div class="unit-switch"><button class="${x.type==='box'?'selected':''}" onclick="changeType(${i},'box')">Box</button><button class="${x.type==='strip'?'selected':''}" onclick="changeType(${i},'strip')">Strip</button><button class="${x.type==='unit'?'selected':''}" onclick="changeType(${i},'unit')">Tablet</button></div></div><input class="qty" type="number" min="1" value="${x.qty}" onchange="setQty(${i},this.value)"><b>Rs. ${fmt(x.price*x.qty)}</b><button class="remove" onclick="remove(${i})">×</button></div>`).join(''):'<div class="empty"><div class="empty-icon">🛒</div><b>No items yet</b><small>Search or scan a medicine, then choose Box, Strip, or Tablet.</small></div>';const s=cart.reduce((a,x)=>a+x.price*x.qty,0),d=Math.max(0,Number(document.getElementById('discount').value)||0);document.getElementById('count').textContent=cart.reduce((a,x)=>a+x.units*x.qty,0)+' units';document.getElementById('subtotal').textContent=fmt(s);document.getElementById('total').textContent=fmt(Math.max(0,s-d));}
function paymentChanged(){const credit=document.getElementById('payment').value==='credit';document.getElementById('customerWrap').style.display=credit?'block':'none';if(!credit)document.getElementById('customer').value='';}
function clearCart(){cart=[];renderCart();document.getElementById('search').focus();}function checkout(){if(!cart.length)return alert('Cart is empty.');const method=document.getElementById('payment').value;const customer=document.getElementById('customer').value;if(method==='credit'&&!customer)return alert('Please select a customer for a credit sale.');const d=Math.max(0,Number(document.getElementById('discount').value)||0),s=cart.reduce((a,x)=>a+x.price*x.qty,0),t=Math.max(0,s-d);let paidValue=document.getElementById('paid').value;const paid=paidValue===''?(method==='credit'?0:t):Math.max(0,Number(paidValue)||0);if(paid>t)return alert('Amount received cannot exceed the sale total.');if(method!=='credit'&&paid<t)return alert('For cash/card sales, amount received must cover the total.');const items=cart.map(x=>({id:x.id,name:x.name,qty:x.units*x.qty,price:x.price/x.units}));const f=document.createElement('form');f.method='post';f.action='index.php?action=sale';[['items',JSON.stringify(items)],['discount',d],['payment_method',method],['paid',paid],['customer_id',customer]].forEach(([n,v])=>{const i=document.createElement('input');i.type='hidden';i.name=n;i.value=v;f.appendChild(i)});document.body.appendChild(f);f.submit();}
document.getElementById('search').addEventListener('input',renderResults);document.getElementById('search').addEventListener('keydown',e=>{if(e.key==='Enter'){const first=document.querySelector('.sell-buttons .mini');if(first)first.focus();}});document.getElementById('discount').addEventListener('input',renderCart);renderResults();renderCart();
</script></body></html>